### ISSUE TITLE
All senders show as null

### ISSUE THREAD

**Issue by Dyason** [mjkaufer/Messer#100]
All of my contacts that message me show as null - message. Replying and sending works, just the sender name is always null. This is in English with no special characters in names.

**Comment by ManolisPapadimitriou** [comment]
Any update on the current issue?

**Comment by tomquirk** [comment]
Hey 👋 *Messer 0.5.1 has just been published* with a bunch of bug fixes - install it and give it a whirl 🤘. If you’re still experiencing this issue, please comment below with your symptoms and we'll keep the ticket open. Thanks for supporting Messer 💬

**Comment by tomquirk** [comment]
This issue hasn't had activity in 14 days, so we're assuming it was fixed in a previous release. If it's still an issue, please open a **new** ticket
