### ISSUE TITLE
Use Messer to send a message in a shell script

### ISSUE THREAD

**Issue by mooooonbaby** [mjkaufer/Messer#101]
Hi,

is it possible to use messer to send a message in a shell script? normally i have to run 'messer' and then send a message with

> m <user> message

I want so send a message when i script is finished, something like

> messer m <user> script finished

Is this possible?

**Comment by tomquirk** [comment]
Hey @mooooonbaby , check out our [Non-interactive mode](https://github.com/mjkaufer/Messer#non-interactive-mode)

**Comment by mooooonbaby** [comment]
Got it, thx.
