### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by mairod** [mjkaufer/Messer#11]
After installing messer, I can't run the command "messer", I get the following error : 

"env: node\r: No such file or directory"

I'm on OSX, am I the first to get this ? :/

**Comment by zg** [comment]
It's because the file format is `dos`.

The way I fixed this was by opening the messer program in vim (`vim /usr/local/bin/messer`) and then typing `:set ff=unix`. Hit enter and then type `:wq`. Now you should be able to run `messer config.json`.

**Comment by mairod** [comment]
Thank you very much, it worked pretty good !
