### ISSUE TITLE
Support deactivated Facebooks accounts that have opted to continue using Messenger

### ISSUE THREAD

**Issue by DilyanMarinov** [mjkaufer/Messer#125]
## Summary

When deactivating a facebook account, you can opt to keep using Messenger without your account reactivating as a result of the login. Messer should support this use case.

## Motivation
Currently, Messer does not respect inactive accounts and your Facebook account is reactivated once you log in using Messer. This persists, even if you deactivate the account after logging in with Messer.

## Concerns
Messer's dependencies might not support this feature.

**Comment by tomquirk** [comment]
Mmm, unfortunately I don't see a way around this. We rely on [this api](https://github.com/Schmavery/facebook-chat-api) so we are bound to whatever they support (which is simply logging in through `facebook.com`) 😢 . I'll add a note to the readme to explain this

**Comment by tomquirk** [comment]
Relevant change -> https://github.com/mjkaufer/Messer#can-i-use-a-deactivated-facebook-account
