### ISSUE TITLE
Make `unread message count` reflect number of conversations with new messages

### ISSUE THREAD

**Issue by TwoLeaves** [mjkaufer/Messer#129]
Messer currently changes the window title to reflect the total unread message count. Could a configuration option be added to make the window title instead reflect the number of conversations with unread messages? That is, if three people have messaged me 5 messages each I want the unread count to be 3, not 15. At least for me and perhaps others, whether a contact has sent 1 new message or 15 new messages is not something that needs to be known at a glance, but rather that 1 or more conversations have new messages.

Not sure if this is worth the trouble of implementing (as it will need some extra logic to check new messages against old unread messages as opposed to just incrementing unreadMessagesCount). For me personally the unreadMessages number is important as it's the only Messer feature I use; I don't use the app as chat client, just a "new message" counter. I replaced the "update window title" function with a "write unread message count to pipe" function, then display that pipe in my OS system tray. I used to use fbcmd for this purpose but since it's gone I couldn't find any other CLI option besides Messer (barring writing my own app using a Messenger API library).

**Comment by tomquirk** [comment]
Hey @TwoLeaves , I like your idea. With an upcoming release we're adding user settings, so we can certainly consider making that a configurable option!

Check out my library [messen](https://github.com/tomquirk/messen) for a lower-level framework for building FB messenger applications :D

**Comment by tomquirk** [comment]
I think your approach should be the standard and we shouldn't add this as a configuration option. Your suggestion is what Facebook does so we should mimic that as close as possible 😄

**Comment by ethan-ou** [comment]
@tomquirk it looks like this could be easily handled in [line 60](https://github.com/mjkaufer/Messer/blob/bb7dca09678b46108f24b3511005b2d37f50fb22/src/event-handlers/message.js#L60) of ```./event-handlers/message.js``` if we replace the line with ```notifyTerminal(new Set(messer.state.threads.unreadThreadIds).size);```.

Are there other considerations I should be aware of?

**Comment by tomquirk** [comment]
I think that would do it! Not sure if you even need the Set, although I could be wrong (may have duplicate ids in there). Happy to accept a PR!

**Comment by ethan-ou** [comment]
My understanding is that ```messer.state.threads.unreadThreadIds``` contains duplicate id's if a user sends more than one message. Turning it into a set would give you the number of users whose messages you haven't read, hopefully fulfilling the issue @TwoLeaves had.

I'll submit a PR soon!

**Comment by TwoLeaves** [comment]
Thanks folks, much appreciated!
