### ISSUE TITLE
messer is failing to run

### ISSUE THREAD

**Issue by phra** [mjkaufer/Messer#13]
hi,
i've just installed messer globally via npm but when i try to launch it it crashes with this error:

`[Wed19:Oct:16 11:13:49] phra@kali ~ $ messer`
`/usr/bin/env: ‘node\r’: No such file or directory`

**Comment by tomquirk** [comment]
@phra should be fixed as of `bcdbf40` 💃

**Comment by wesmcouch** [comment]
The new version isn't published yet, but if you want to get it to work with the current version install dos2unix with:
`brew install dos2unix`
then run the command on index.js of wherever messer is installed
`dos2unix index.js`

**Comment by mjkaufer** [comment]
@phra I just published the new version to npm so give it another try now!

**Comment by phra** [comment]
@mjkaufer yeah, now it works.
