### ISSUE TITLE
Only contacts working properly

### ISSUE THREAD

**Issue by blandre** [mjkaufer/Messer#133]
### Description

I cannot seem to get anything other than the contacts command to work. I had both fb-messenger-cli and messer installed, but neither of them was working properly. I tried to uninstall (not 100% successfully) and install again (seemed successful). Messer logs in OK, but the only command I get a response is with contacts. Any suggestions on how to do a clean install or to solve this issue?

### Versions

Run and copy-paste the results of the following:

- npm -v 6.4.1
- node -v v11.9.0
- messer -v 0.5.0

Ubuntu 18.04 LTS

**Comment by tomquirk** [comment]
Hey @blandre sorry to hear you're having trouble. The latest vestion of Messer is 0.6.0, so I'd suggest trying to upgrade to this version and see if you have any success. Let us know! Please reopen this issue if you need more assistance
