### ISSUE TITLE
failed to login

### ISSUE THREAD

**Issue by younlok** [mjkaufer/Messer#141]
### Description

> Description of the issue
i installed it and when i run it and enter my details i get error 

**Expected behavior:** [What you expect to happen]
i expected it to run
**Actual behavior:** [What actually happens]
Failed to login: Error inside first pull request. Received HTML instead of JSON. Logging in inside a browser might help fix this.

### Versions

- npm -v
6.13.6

- node -v
v12.13.0
- messer -v
0.7.1

i run arch linux 64 bit

**Comment by wolfiex** [comment]
Replicated

**Comment by tomquirk** [comment]
@younlok thanks for raising this 🙏 

Whats the error you're getting? How does Messer behave specifically?

**Comment by wolfiex** [comment]
The phrase:

> "Failed to login: Error inside first pull request. Received HTML instead of JSON. Logging in inside a browser might help fix this"

as well as obviously failing to log on. One of the other facebook clis also has an issue recently, so I wonder if Facebook themselves have changed something.

**Comment by tomquirk** [comment]
Oh damn, haha. Thanks for clarifying.

Issue has been raised in the API we use: https://github.com/Schmavery/facebook-chat-api/issues/794. I will follow and update you all here... thanks for you patience 👌

**Comment by younlok** [comment]
i think this is because the 2fa maybe ??

**Comment by tomquirk** [comment]
Can I suggest you all try running:

```
$ messer cleanup
```

Someone on one of those issues suggested clearing some state might fix issues...

**Comment by younlok** [comment]
worked

**Comment by jamie-emb** [comment]
I have the same issue, attempted the fix you suggested and still get the same error
