### ISSUE TITLE
What does the setting SHOW_TYPING do?

### ISSUE THREAD

**Issue by krunoPeric** [mjkaufer/Messer#156]
## Summary

> I set SHOW_TYPING and SHOW_READ to true, but I don't see any differences in the program output.  I thought maybe SHOW_TYPING would display some kind of status message like "<thread_name> is typing..." to STDOUT.

## Motivation

> I think it would be a great feature to have, if possible.

## Additional note

I might not be understanding what those settings are supposed to do.  Not sure if this is a bug or a feature request...

**Comment by tomquirk** [comment]
@krunoPeric 

- `SHOW_TYPING` currently does nothing. The intention is that it will show the user your are typing to, that you are indeed typing (e.g. `krunoPeric is typing...`, in the FB UI)
- `SHOW_READ` shows marks messages sent to you as READ when you use the `clear` command (see [the docs](https://github.com/mjkaufer/Messer#supported-settings))
