### ISSUE TITLE
2FA?

### ISSUE THREAD

**Issue by joech4n** [mjkaufer/Messer#16]
Does this app support Facebook's 2FA?

I'm seeing the following:

    $ messer config.json
    info Logging in...
    ERR! Error in login: login-approval
    { error: 'login-approval', continue: [Function: continue] }

**Comment by mjkaufer** [comment]
Theoretically, it's possible with the API we're using, but it hasn't been implemented yet. Relevant docs are [here](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#login)

**Comment by coreice** [comment]
I guess 2FA can be avoided via app-specific passwords, but it seems this is not working?

**Comment by bzyg7b** [comment]
not working for me either

**Comment by coreice** [comment]
Is there any sight on a fix for this problem?

**Comment by tomquirk** [comment]
Sure thing, but I won't have time for at least another month. Will get onto it asap though :)

**Comment by Natfan** [comment]
Bump? :)

**Comment by tomquirk** [comment]
Made an attempt [here](https://github.com/tomquirk/Messer/commit/da6c5f97852248032007eb7bb27d3cc6fb5759ad)...it didn't work for me, Facebook didn't want to trust me (persistently). Would be awesome if you guys could test @joech4n @coreice @Natfan. Help wanted!

**Comment by coreice** [comment]
@tomquirk Thanks for picking this up. I tried to log in with a freshly generated app-specific password but it failed:

```
 info login Logging in...
ERR! login Wrong username/password.
{ error: 'Wrong username/password.' }
```

**Comment by tomquirk** [comment]
That is indeed the one/s. I tried with `forceLogin` as well to no avail. I'm hoping this is a problem with the API - would be good if someone could confirm this (I will soon enough)

**Comment by tomquirk** [comment]
Okey-dokey folks.

Using Messer with a 2FA-enabled Facebook account is now possible! (kinda). Take a look at the `refactor` branch and consult the README for a guide.

**Comment by forcemagic** [comment]
It was in the API, I fixed it yesterday. :smiley: It should work now.

**Comment by tomquirk** [comment]
yeessss @forcemagic !!!, Just saw that ticket closed. Will sort this out in the near future

**Comment by tomquirk** [comment]
Sorted now 👍 @mjkaufer reckon you can add me to the Messer npm list so I can publish? (or, can you publish latest?)

**Comment by mjkaufer** [comment]
I'll try to have it published and have you added to npm by the weekend -
hmu with your npm name.

Thanks for looking over all of this!

**Comment by tomquirk** [comment]
tomquirk pretty sure 🌮

**Comment by mjkaufer** [comment]
@tomquirk just pushed new version & added you to npm
