### ISSUE TITLE
How safe is it to use Messer?

### ISSUE THREAD

**Issue by Ravichandra-C** [mjkaufer/Messer#166]
Hi Team,

I'm planning to use Messer with my personal facebook id, but I'm not sure how safe it is to give password/user name to Messer.Main reason is because I'm not understanding how messer is actually working. Can someone please let me know how safe it is to use Messer?

**Comment by tomquirk** [comment]
Hey @Ravichandra-C - see README for what happens to your username and password: https://github.com/mjkaufer/Messer#do-you-store-any-of-my-data

In short, your username and password are never stored anywhere. You are authenticated with Facebook using this library: https://github.com/Schmavery/facebook-chat-api.

We _do_ store your "appState", which includes some kind of auth token that is used to authenticate you.
