### ISSUE TITLE
Group chats

### ISSUE THREAD

**Issue by 2016rshah** [mjkaufer/Messer#2]
Add support for messaging group chats! 

(@ 3 rpm)

**Comment by mjkaufer** [comment]
Tru

**Comment by chauchinyiu** [comment]
still not yet implemented?

**Comment by tomquirk** [comment]
Messages from group chats will come through, but there's no way to distinguish them. Can't send a message to a group either...Pretty sure the data's there tho

**Comment by mjkaufer** [comment]
I'm pretty sure the "reply" mechanic works for groups but I think that's it.

**Comment by tomquirk** [comment]
Messer now supports group chats to a usable extent. There's still more we could do around it, but will close this now.
