### ISSUE TITLE
Doesn't work with two-factor authentication

### ISSUE THREAD

**Issue by DobaKung** [mjkaufer/Messer#20]
![screen shot 2559-12-25 at 11 55 21 pm](https://cloud.githubusercontent.com/assets/3814520/21472131/a27a4c68-cafd-11e6-839f-9ccfedd6d9ea.png)

**Comment by tomquirk** [comment]
Hey @DobaKung, as discussed in #16, the support in the API is there, just not implemented in Messer as of yet.

**Comment by tomquirk** [comment]
Closing, duplicate of #16
