### ISSUE TITLE
Error upon receiving some messages

### ISSUE THREAD

**Issue by MichaelRupertDev** [mjkaufer/Messer#24]
When i received a "wave" from a new friend, he following error was presented.

```[TypeError: Cannot read property 'fullName' of undefined]```

I've gotten it before from thumbs up, I believe.

**Comment by tomquirk** [comment]
I may have fixed it in [this commit](https://github.com/mjkaufer/Messer/commit/1b3a3c2f6e42441399c2c04eeb61bd283069e9fc).

I don't think the `facebook-chat-api` is consistent with names for things 🤔. I'll test it later when I can be bothered to make a fake fb account 😄

**Comment by tomquirk** [comment]
Closing for now - if you feel this issue hasn't been resolved, please create a _new_ ticket, referencing this one (#24)
