### ISSUE TITLE
Messer Logo

### ISSUE THREAD

**Issue by tomquirk** [mjkaufer/Messer#25]
Let's get a dank logo

**Comment by tomquirk** [comment]
![messer-logo](https://user-images.githubusercontent.com/12551741/27252310-6655f4f6-539e-11e7-978b-c8eaba02ba68.png)

**Comment by tomquirk** [comment]
Closing for now. Feel free to open if you've got better ideas

**Comment by mjkaufer** [comment]
Hey @tomquirk just wanna say the logo looks dope

**Comment by tomquirk** [comment]
Ay cheers dude 🎉
