### ISSUE TITLE
Cannot send message to oneself

### ISSUE THREAD

**Issue by fbukevin** [mjkaufer/Messer#29]
This might not necessary but this operation is work in Facebook Messenger.

I can find myself(my Facebook account name is "Veck Hsiao") and send a message to myself. This seems not work in Messer.

```
> message "Veck Hsiao" OH!!!
User "Veck Hsiao" could not be found in your friends list!
```

**Comment by Smile4ever** [comment]
Confirmed, this does not work.

**Comment by mjkaufer** [comment]
Correct - I figured it wouldn't be a very common use case, but if we were to add the `selfListen` key and set it to `true` on line 280, you'd be able to do so.

**Comment by tomquirk** [comment]
For the meantime, I've added a function `getUserByID` which first checks if the given ID is that of the current user (see [here](https://github.com/mjkaufer/Messer/blob/refactor/helpers.js#L55)). Defs open for critique.
