### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mjkaufer** [mjkaufer/Messer#3]
Messer is not working right now due to an error in one of its dependencies - `facebook-chat-api`. The issue has been fixed [here](https://github.com/Schmavery/facebook-chat-api/issues/30), but we have to wait for the new package module to be pushed to npm for Messer to be able to use it (see [this](https://github.com/Schmavery/facebook-chat-api/issues/34) issue)

**Comment by Schmavery** [comment]
Hopefully this is fixed now! :)

**Comment by mjkaufer** [comment]
`facebook-chat-api` is fixed for sure, but I'm getting the same message when I run `messer`. I've updated the dependency version and uninstalled `messer@0.1.1`, but I still get that error. However, when I manually run `index.js` with `node`, I don't get the error. Hmmmmm.

**Comment by mjkaufer** [comment]
Just kidding, this was caused by a poor npm environment I had set up.
