### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by tomquirk** [mjkaufer/Messer#31]
For better UX, some colors should be incorporated in the REPL log. At a minimum, there should be different colors per chat for easier scanning. Perhaps also the ability to set color per chat, or even get the 'real' color (as it was set in the app or the website) if available.

**Comment by mjkaufer** [comment]
`facebook-chat-api` has a method [getThreadInfo](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#getThreadInfo) that could accomplish this - combined with [chalk](https://www.npmjs.com/package/chalk), this would probably be easy enough to get working

**Comment by tomquirk** [comment]
sweeeeet, sounds 👌

**Comment by tomquirk** [comment]
gonna call this done for now. There's still more we could do around colors, but the basic functionality is in place
