### ISSUE TITLE
Refactor - code review and testing

### ISSUE THREAD

**Issue by tomquirk** [mjkaufer/Messer#33]
It's about time for some code review! @mjkaufer @2016rshah `@anyone else`

I've put at least a little bit of thought as to better architecture for the project going forward but would definitely like some more opinions. Especially towards:

- whether functions in the `helpers` file should be part of the Messer prototypes (I'm starting to think yes)
- caching data structures (I'm sure there are more efficient ways)
- Messer instance - should everything be a prototype, better abstractions. etc.

And test! The best way I've found is just to keep it running for a day and find little edge-cases.

It would be awesome if you guys could spare an hour or so to have a gloss. I haven't fleshed out docs/comments so if you've got any questions just comment here 🎉

**Comment by jwpaine** [comment]
Would love to contribute to such a project! For refactoring, what about splitting index.js into two files, one facebook.js to abstract away the complexity of the API with exported functions, and another, interface.js, receiving callbacks, interfacing with the API, and taking user input? great stuff thus far!

**Comment by tomquirk** [comment]
@jwpaine - great suggestions. If you haven't already take a look at the [refactor](https://github.com/mjkaufer/Messer/tree/refactor) branch. 

We could certainly abstract some of the API away, however, I'd like to hear/see your thoughts on what exactly that would entail. I don't feel the API is so complex as to warrant it for the project at this stage and I'm not sure how much value would be added in doing so. Very happy to be proven wrong, though! Feel free to branch off [refactor](https://github.com/mjkaufer/Messer/tree/refactor) and whip up an example.

Would also love some criticism on the dot points listed on this ticket if you have any!

**Comment by tomquirk** [comment]
v0.2 is out!
