### ISSUE TITLE
Add Color to text produced by Program (Such a new message from)

### ISSUE THREAD

**Issue by trappekoen** [mjkaufer/Messer#36]
When you receive a message from someone mid-conversation with someone else, or mid-typing, it gets really confusing. May I suggest simply adding color to new message (and possibly other) statements?

This can be done simply like this (for cyan blue):

console.log('\x1b[36m%s\x1b[0m', 'I am cyan');  //cyan

**Comment by tomquirk** [comment]
hey @trappekoen ,

I've implemented this to some extent in the `refactor` branch. Currently, it will set the color to the color of the conversation on Facebook, but I'm open to making it random. 

Check #31 for more
