### ISSUE TITLE
Send images as attachments

### ISSUE THREAD

**Issue by TKasperczyk** [mjkaufer/Messer#38]
It would be nice if we could send images in chat by typing a path to an image file. It's possible with facebook-chat-api:

```
   let msg = {
        body: "",
        attachment: fs.createReadStream(__dirname + '/image.jpg')
    }
    api.sendMessage(msg, yourID);
```

**Comment by tomquirk** [comment]
Love it. Let's hold off on this until refactor or is merged 😀

**Comment by tomquirk** [comment]
v0.2 is out! feel free to submit pr's for this
