### ISSUE TITLE
Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by PandawanFr** [mjkaufer/Messer#44]
Hey, when I try to use messer (clean install), it appears that I am unable to use/create a config.json file.

I just installed it with `npm install -g messer` and then ran `messer` and got this error
```
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at ReadFileContext.fs.readFile [as callback] (/usr/local/lib/node_modules/messer/src/helpers.js:50:39)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```
and when I checked in the code, it appeared that it was unable to create a config.json file.

I don't know if it's an error on my part or the code has a problem. 

Btw, I'm using node `8.9.2` and npm `5.6.0`.

Thanks!

**Comment by tomquirk** [comment]
yep, issue has been fixed but not yet released on npm. For the meantime, reference this repo directly 😄 

On that note, I'll create a new label "ready for release" (or similar) so that issues that are "done" but not released to npm can be identified.

@mjkaufer when you get a chance, could you do the npm things? 😸

**Comment by tomquirk** [comment]
closing as no similar issues have been reported

**Comment by PandawanFr** [comment]
Hey, I decided to try again just to see if it worked, but it still doesn't.
![image](https://user-images.githubusercontent.com/8564550/41243632-7f824b68-6d57-11e8-8481-e91b93d7073e.png)

**Comment by shekoufepourkan** [comment]
I had this Problem too. But i solved it. how? =D with this Way: Your json file is probably your code's folder. Move the code to another folder and redirect it.
