### ISSUE TITLE
Enabling 2FA does not allow you to log in

### ISSUE THREAD

**Issue by n1889** [mjkaufer/Messer#5]
When two factor auth is enabled (code generator in app) the client becomes unusable with the following error.

```
messer ~/Desktop/config.json
info Getting login form data
info Logging in...
[Error: Error retrieving userId. This can be caused by a lot of things, including getting blocked by Facebook for logging in from an unknown location. Try logging in with a browser to verify.]
Unhandled rejection TypeError: expecting an array, a promise or a thenable
```

**Comment by mjkaufer** [comment]
@n1889 This is a problem with the unofficial FB Messenger API Messer is using - [facebook-chat-api](https://github.com/Schmavery/facebook-chat-api). I would raise this issue in their repository, as I think they would know more about it.

At a cursory glance, it looks like `facebook-chat-api` has 2FA on their roadmap, but haven't implemented it yet. Check out https://github.com/Schmavery/facebook-chat-api/issues/53

**Comment by bsansouci** [comment]
Yup yup we're working on it, v1.0 should roll out in a couple of days.

**Comment by mjkaufer** [comment]
Thanks! :heart:

**Comment by Karlheinzniebuhr** [comment]
still having this issue

**Comment by schutzsmith** [comment]
I'm having the same problem. Always failing to login because of 2fa
