### ISSUE TITLE
Support non-interactive mode

### ISSUE THREAD

**Issue by joech4n** [mjkaufer/Messer#58]
Is there a way to invoke messer in a non-interactive mode? For example, I'd like to use it with [Alfred app](https://www.alfredapp.com/) and call it like this:

`messer m "Bob" hi`

**Comment by tomquirk** [comment]
cool idea @joech4n , would be happy to consider PR's adding this support 👍

**Comment by tomquirk** [comment]
released as of https://github.com/mjkaufer/Messer/milestone/3. Thanks again @SUBmarinoff !!
