### ISSUE TITLE
Always getting the help syntax error

### ISSUE THREAD

**Issue by yanelev** [mjkaufer/Messer#6]
I follow your steps but I keep getting :

Invalid command - check your syntax
Commands:
 message "[user]" [message]
 reply [message]

I user message and reply both the same. Although I am getting incoming messages.

**Comment by mjkaufer** [comment]
Hey @yanlev,

My friend was getting a similar problem - for some reason, his CLI was adding a hidden parentheses to the input or something, which was messing stuff up. I'll try and write a fix this evening, if everything goes well.

**Comment by yanelev** [comment]
Ok thanks I will wait

**Comment by mjkaufer** [comment]
@jeon97

**Comment by yanelev** [comment]
Is there anyone who can answer my question?

**Comment by tomquirk** [comment]
@yanelev still having issues?

**Comment by lamons** [comment]
I got syntax error when using the short command e.g. `m "[user]" [message]`. but it works fine using the complete command.

**Comment by tomquirk** [comment]
hey @lamons can you give us a specific example of the command you used?

**Comment by lamons** [comment]
Hi, for example when I use `m "anna" hello` or 'r yes' I got error
message `Invalid command - check your syntax` but when I use `message`
and `reply` instead of `m` and `r` the message went correctly.

**Comment by tomquirk** [comment]
ah, @mjkaufer think the npm repo isn't up to date. @lamons until its updated, clone this project directly and you should be able to use shortcuts 😄

**Comment by lamons** [comment]
Ah I see... Thanks!

On Tue, Apr 18, 2017 at 0:14, Tom Quirk <notifications@github.com> wrote:
ah, @mjkaufer [https://github.com/mjkaufer] think the npm repo isn't up to date. @lamons [https://github.com/lamons] until its updated, clone this project directly and you should be able to use shortcuts 😄

**Comment by tomquirk** [comment]
@mjkaufer once we update npm this ticket can be closed 😃

**Comment by mjkaufer** [comment]
Pushed the new stuff to npm - lemme know if it works <3

**Comment by lamons** [comment]
Still got same errors - the version number is 0.1.12

**Comment by tomquirk** [comment]
I just installed via npm, all good for me. Check your node version - I don't have time to test them atm but I'm running v7.9.0, I have a feeling LTS will be fine though.

**Comment by lamons** [comment]
Ah it works.. was a stupid mistake, the program works well. Thanks!

**Comment by tomquirk** [comment]
Awesome! 🌮
