### ISSUE TITLE
Group chats - group name and sender name is null

### ISSUE THREAD

**Issue by y0l016** [mjkaufer/Messer#63]
Other people's usernames are displayed as undefined
![edit2](https://user-images.githubusercontent.com/33809736/40877851-0de1bdda-66a5-11e8-993f-8afd02921f7b.gif)
I am not sure why this happened

**Comment by tomquirk** [comment]
Hey @Mshanmuganathan, I just pushed a decent-sized update, something may have broken. 
Can you let us know:
* What version of Messer you are running
* What version of Node you are running
* If that person is a friend of yours

I think I fixed most of the bugs in `v0.3.2` - try that version if you aren't already on it 😄 

Thanks!

**Comment by tomquirk** [comment]
Ah okay, I will have to check group chats.

Could you run the following to confirm what version of Messer you are using? (it should be `0.3.3`)

```bash
npm list -g | grep messer
```

**Comment by tomquirk** [comment]
Gotchya, group chats is broken 😂 

Sorry about that @Mshanmuganathan . A fix is probably about a week away.

**Comment by Mshanmuganathan** [comment]
lol. Thanks btw

**Comment by Mshanmuganathan** [comment]
The version is 0.3.2

**Comment by tomquirk** [comment]
Hey 👋 **Messer 0.5.1 has just been published** with a bunch of bug fixes - install it and give it a whirl 🤘. If you’re still experiencing this issue, please comment below with your symptoms and we'll keep the ticket open. Thanks for supporting Messer 💬

**Comment by tomquirk** [comment]
This issue hasn't had activity in 14 days, so we're assuming it was fixed in a previous release. If it's still an issue, please open a **new** ticket
