### ISSUE TITLE
Aggregated History View

### ISSUE THREAD

**Issue by y0l016** [mjkaufer/Messer#65]
## Summary
Add a command that will provide an "overview" of your Messenger state. Thinking default to top 5 chats, and show the 5 most recent messages of each chat.

I think we could simply extend the `recent` command, and add a `--history` option.

## Motivation

Tedious to achieve the same thing with the current mechanisms

## Original issue

Please add history of chats function. This client lacks it badly. I very much love the client. Hope you'll add history soon

**Comment by tomquirk** [comment]
`history "you friend's name"`

**Comment by Mshanmuganathan** [comment]
I meant like default display of full chat history when you log in with unread on first.

**Comment by tomquirk** [comment]
hmm, not quite sure what you mean! 😂 Possibly you are looking for the `recent` command? That will list your 5 (or however many you specify) recent chats and color them red if there are unread messages in there.

If that's not what you're after, give me a specific description (preferably with an example), and I'm sure we can figure something out 😄

**Comment by Mshanmuganathan** [comment]
Thanks for the good response.
What I meant is, like this: 
![image](https://user-images.githubusercontent.com/33809736/41019408-1d0f07b6-697c-11e8-9a4c-4d0bad45f49d.png)

**Comment by tomquirk** [comment]
Right, I get what you mean. Definitely a good suggestion.

Currently, we aren't in a position to do specifically what you are asking, but it's definitely something that has been discussed before and we will eventually do.

Might be a good holiday project for me/someone else 😂
