### ISSUE TITLE
[Question] Where are the default credentials?

### ISSUE THREAD

**Issue by eupiteco** [mjkaufer/Messer#69]
I logged in the first time and did now I auto-login everytime, but did not asked messer to save my credentials. I'm kinda freaking kniwing my fb credentials are somewhere in the computer and I can't find them. 
Already looked in my home folder, ~/.config and /usr/lib/node_modules/messer but did not managed to findo the file... 

Thanks in advance :smile:

**Comment by tomquirk** [comment]
Hey @eupiteco, not at my computer right now, but, put your mind at ease...

On login, facebook-chat-api allows to save "appState" (literally `appState.json`), which we utilise to save you having to enter your creds. I'm pretty sure that file is just a session token of sorts, but I would have to double check. Relevant code for saving the app state is in `util/helpers.js`

**Comment by eupiteco** [comment]
Yeah, that worked out. 
found `appstate.json` in my home folder, from where I launched messer. Theres was no explicit values of my credentials but once I deleted the file, messer aked for them.
I'm kinda totally newb with js so excuse my rushing.
I guess this thread can be closed now, thanks for yout attention.

**Comment by tomquirk** [comment]
all good man! Glad to help
