### ISSUE TITLE
is there command to logout from messenger?

### ISSUE THREAD

**Issue by dominikradko** [mjkaufer/Messer#70]
Can't see it anywhere. Just want to logout because i want to keep it private

**Comment by waxyhexagon** [comment]
From the readme:

> After you've successfully logged in, an appstate.json file is created which should allow you to skip this process every time you log in. If you wish to "start over", just delete that file.

**Comment by tomquirk** [comment]
I'll add this to the docs explicitly, thanks @dominikradko !

**Comment by dominikradko** [comment]
Thank you @tomquirk !

**Comment by tomquirk** [comment]
Released as of https://github.com/mjkaufer/Messer/milestone/3

In a messer session, use the command `logout` 💃
