### ISSUE TITLE
Lock on to user and send messages

### ISSUE THREAD

**Issue by SUBmarinoff** [mjkaufer/Messer#72]
It would be nice to have a command to "lock on" to a user and chat just with them. I find myself sending the wrong message to the wrong person sometimes, when I use the r command.

Example:
```
> lock "User1"
> my message // Sent to User1
> another message // Sent to User1
> .unlock
> // free to type commands again
```

**Comment by tomquirk** [comment]
Done!

**Comment by michondr** [comment]
hey, this is an awesome feature, I can have one terminal locked to each person I want.

however, why are shown messages from other people? am I using the feature as intended?

on the left, `Esk8 Prague riders crew` is locked, on the right `Petra Červená` is locked. whoever incoming messages are shown in both the terminal windows. it's a bit messy after a while
 
![image](https://user-images.githubusercontent.com/29277166/87870346-65088500-c9a7-11ea-88f5-a4663281c58f.png)
