### ISSUE TITLE
How To Execute Shell Command with Python

### ISSUE THREAD

**Issue by crissmil** [mjkaufer/Messer#83]
Hi, I am trying to use messer in my home automation system. I want to receive on fbk messages from home. I installed messer on Raspberry where I have a py socket server which communicates with my Fibaro home automation.  Messer is working good from lxterminal, but I need to send text command from os shell script, because my socket server uses   os.system()  function to run it.

I only managed to pass login process like this:
lxterminal --command="/bin/bash -c '/home/pi/node_modules/messer/index.js; read'"

Is there any other way to achieve my goal?

**Comment by crissmil** [comment]
Hi there,
I succeeded to use messer to send messages from my home automation using xdotool, by calling strings like this:

'"xdotool type m' '" .. '\\"Fibaro\\"' .. '" "' .. fbk_message' 

from socket server client. And it is working fine. Thanks for your amazing work.

I am pushing a little further now... I want my Sonos to speak text received in terminal log(). I am thinking to add shell system command to messer.js but I am new to js and I do not know how. In python there are 2 optins: 
by using import os, then use os.system(received_data) or 
by using import subprocess, then use subprocess.call(received_data). 
Is there an equivalent in js?
Thanks.

**Comment by crissmil** [comment]
my Sonos server is listening to this shell comands:
'wget "http://localhost:5005/Living%20Room/say/'.. text ..'/Andrei/'.. ttsvol ..'"'     or
'curl http://localhost:5005/Living%20Room/say/'.. text ..'/Andrei/'.. ttsvol ..''

I just need something like this:

import os
data = 'wget "http://localhost:5005/Living%20Room/say/'.. text ..'/Andrei/'.. ttsvol ..'"'
os.system(data)

but in js...

**Comment by crissmil** [comment]
I found this working:

function execute(command) {
        const exec = require('child_process').exec
        exec(command, (err, stdout, stderr) => {
          process.stdout.write(stdout)
        })
      }
      execute('curl http://localhost:5005/Living%20Room/say/Hi%20There!/Andrei/30')

now I just need to know how to integrate it into messer in order to get the received text and add it to command execute()

**Comment by crissmil** [comment]
Did it! added this to event_handler.js just under log()

function execute(command) {
          const exec = require('child_process').exec

          exec(command, (err, stdout, stderr) => {
            process.stdout.write(stdout)
          })
        }
        
        messageSay = encodeURIComponent(messageBody.trim())
        execute('curl http://localhost:5005/Living%20Room/say/' + messageSay + '/Andrei/30')

Next chalenge is to control my home automation by text message. Just like a personal bot :)

**Comment by crissmil** [comment]
Facebook just killed my boot today... after 1 week of work... useless...

**Comment by tomquirk** [comment]
Hey @crissmil, really sorry to hear your account got banned. It is an occasional unfortunate consequence of using projects of this nature.

I've been working on a new project called [messen](https://github.com/tomquirk) which may be of use to you (although it _is_ still in Nodejs). Messen now powers Messer (this project). Any feedback appreciated ✌️
