### ISSUE TITLE
Question: Where are messages stored?

### ISSUE THREAD

**Issue by andmib** [mjkaufer/Messer#84]
Hello there,

Thanks for the awesome tool. I have a question about message storage. Where are received/sent messages cached/stored? Are they encrypted on the HD, or stored in plaintext?

Thanks!

**Comment by tomquirk** [comment]
Hey @andmib , glad to hear you like the project.

We don't store messages 🎉 We only go as far as metadata, and no, none of this is encrypted.

See [the Messer class](https://github.com/mjkaufer/Messer/blob/b5518a1d521af6063fd3efc1ff3132c513af9d72/src/messer.js#L16) and [it's cacheThread method](https://github.com/mjkaufer/Messer/blob/b5518a1d521af6063fd3efc1ff3132c513af9d72/src/messer.js#L205). You'll see that as far as we go is:
```js
this.threadCache[thread.threadID] = {
    name: thread.name,
    threadID: thread.threadID,
    color: thread.color,
    lastMessageTimestamp: thread.lastMessageTimestamp,
    unreadCount: thread.unreadCount,
  } // only cache the info we need
```

Hope this helps!
