### ISSUE TITLE
Distinguish between contacts with same name.

### ISSUE THREAD

**Issue by phasstw** [mjkaufer/Messer#86]
## Summary

the `contacts` command should distinguish between different users who have the same name. I have two friends with the same name and they are only showing up as one entry in the output of `contacts`.

**Comment by tomquirk** [comment]
Hey 👋 **Messer 0.5.1 has just been published** with a bunch of bug fixes - install it and give it a whirl 🤘. If you’re still experiencing this issue, please comment below with your symptoms and we'll keep the ticket open. Thanks for supporting Messer 💬

**Comment by tomquirk** [comment]
Hey 👋 We recently released a new version of Messer with a bunch of bug fixes - install it and give it a whirl 🤘. If you’re still experiencing this issue, please comment below with your symptoms and we'll keep the ticket open. Thanks for supporting Messer 💬
