### ISSUE TITLE
Group Messages not displaying individual names

### ISSUE THREAD

**Issue by phasstw** [mjkaufer/Messer#87]
When I receive a group message, the individual participents are not named. This makes group chats impossible to participate in. Either the group name is repeated or null is inserted for both the group and the participant.

Ex. (Group Name) Group Name - Message Here
OR
(null) null - Message here

**Comment by tomquirk** [comment]
Hey 👋 **Messer 0.5.1 has just been published** with a bunch of bug fixes - install it and give it a whirl 🤘. If you’re still experiencing this issue, please comment below with your symptoms and we'll keep the ticket open. Thanks for supporting Messer 💬

**Comment by tomquirk** [comment]
This issue hasn't had activity in 14 days, so we're assuming it was fixed in a previous release. If it's still an issue, please open a **new** ticket
