### ISSUE TITLE
Logging in to Messer causes FB to lock account

### ISSUE THREAD

**Issue by xujenna** [mjkaufer/Messer#91]
### After chatting on Messer for about ten minutes, Facebook logged me out of all my devices and locked my account: 

<img width="554" alt="screen shot 2019-02-08 at 3 21 34 pm" src="https://user-images.githubusercontent.com/13280722/52505599-050a8e00-2bba-11e9-97a5-38386caa6075.png">

### Steps to Reproduce

1. use Messer
2. get locked out of Facebook account
3. change fb password
4. Messer attempts to login using old credentials and fails; doesn't offer a way to change them
5. uninstall and reinstall the package
6. new install inexplicably continues to attempt to login with old credentials, despite there being no appstate.json file

**Expected behavior:** Messer would prompt me to login after reinstalling the package

**Actual behavior:** 
```
➜  ~ messer
Logging in...
Error: Failed to login as [undefined] - [object Object]
    at facebook (/usr/local/lib/node_modules/messer/src/messer.js:108:27)
    at /usr/local/lib/node_modules/messer/node_modules/facebook-chat-api/index.js:446:7
    at tryCatcher (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate (timers.js:637:19)
    at process.topLevelDomainCallback (domain.js:120:23)
```

### Versions

Run, and copy-paste the results, of the following:
  - npm -v 6.5.0
  - node -v v11.9.0
  - messer -v 0.4.2

Running macOS Sierra 10.12.6

Thanks!

**Comment by tomquirk** [comment]
Hi @xujenna ,
Very sorry to hear you're having troubles. Firstly, congratulations for submitting the best bug report in this project's history 🙏

I'll try and reproduce your issue, but in the interim, here are a few comments:

1. Any temporary locking/red flags that Facebook might raise is mostly out of our control. Messer is powered by [facebook-chat-api](https://github.com/Schmavery/facebook-chat-api), and so anything like this is generally on them. Someone recently opened [this issue](https://github.com/Schmavery/facebook-chat-api/issues/707), so it seems they may be having some problems. I'll keep an eye on this issue and make sure we're up to date with them.

2. Regarding password stuff, we save your appstate in `~.messer/` - I would try wiping that directory. The non-existence of an appstate file within that directory will prompt you for your password. Let us know if you're still having issues. I will consider adding a "start fresh?" option upon starting Messer that will allow you to wipe your app state and start clean every time.

3. I'll look at improving that login error message - it's certainly not very helpful as it stands.

**Comment by tomquirk** [comment]
I've been testing fairly heavily for the last 24 hours and haven't stumbled across any temporary locking on my main account. However, I have a test account which did trigger a "upload a photo to prove it's you" lock.

I have just released a new version, v0.5.0, which adds a `cleanup` command. Usage:
```bash
$ messer cleanup
```
This will forcibly remove your appstate.

Eager to hear if you have any more issues

**Comment by xujenna** [comment]
Thanks for the quick turnaround, Tom! 

I deleted `appstate.json` from `~.messer/` and doing this, in conjunction with enabling 2FA, seemed to have done the trick—Messer prompted me to login and enter my 2FA code, Facebook asked me to confirm my login, and ever since I've been happily chatting through Messer, without getting locked out once. 🙌

Thanks again for looking into it!

**Comment by tomquirk** [comment]
I was feeling productive 😂 Glad to hear it though 😎

**Comment by krunoPeric** [comment]
Similarly, I've been getting locked out of FB and see this error message when i try to login to FB:

![image](https://user-images.githubusercontent.com/13294525/85184137-4736eb80-b254-11ea-977d-99a76d5f60fd.png)

I just turned on 2FA so fingers crossed :crossed_fingers: 

Thanks for making this nice bug report!  It looks *crisp*

**Comment by DanielEliasib** [comment]
I know this is old but i got something similar today, this time facebook locked me out of my account and showed me that someone was trying to login from MacOs (which is no my operating system) and from a different ip than mine, it was just after login into messer, is this expected behavior? Why facebook thinks I'm trying to connect from different ip and OS?

**Comment by tpargmdiaz** [comment]
Hi,  I have just installed messer but I am unable to login and I get message below:

Failed to login: Wrong username/password.

Checked credentials on the browser and they are ok.
