### ISSUE TITLE
can't escape quotes in non-interactive mode

### ISSUE THREAD

**Issue by xujenna** [mjkaufer/Messer#93]
### Steps to Reproduce

1. `messer --command='m "John Smith" Hey what\'s up'`
2. Messer breaks strangely, sends nothing, returns no error

**Actual behavior:** 
```
messer --command='m "John Smith" Hey what\'s up' 
quote>
```

### Versions

  - npm -v 6.5.0
  - node -v 11.9.0
  - messer -v 0.4.2

Thanks!

**Comment by tomquirk** [comment]
hey @xujenna , thats a bash thing afaik. Try `node index.js --command="m \"John Smith\" Hey what's up"` instead
