### ISSUE TITLE
Some cyrillic showing as null

### ISSUE THREAD

**Issue by MrGKanev** [mjkaufer/Messer#98]
### Description

Some of the friends who write to me have they're named as "null". I tried with one group and it worked it showed it as it should. I couldn't see a logic behind it or at least for now.

### Steps to Reproduce

1. Most of the people who I have with Cyrlic names are null

**Expected behavior:** 
See his real name.
**Actual behavior:** 
See "null" and the message

### Versions

Run, and copy-paste the results, of the following:
  - npm -v -> 6.7.0
  - node -v -> v11.12.0
  - messer -v -> 0.5.0

Also, please include the OS and what version of the OS you're running.
MacOS Mojave v 10.14.3

**Comment by tomquirk** [comment]
Hey 👋 **Messer 0.5.1 has just been published** with a bunch of bug fixes - install it and give it a whirl 🤘. If you’re still experiencing this issue, please comment below with your symptoms and we'll keep the ticket open. Thanks for supporting Messer 💬

**Comment by MrGKanev** [comment]
Hey @tomquirk , how can I update?

**Comment by tomquirk** [comment]
should just be able to run `npm install -g messer` again, check you've got 0.5.1 or 0.5.2 installed with `messer --v`
