### ISSUE TITLE
sending Group Messages not working 

### ISSUE THREAD

**Issue by psiriders** [mjkaufer/Messer#99]
### Description

Group Messages from CLI doesn't work 

### Steps to Reproduce

# messer --command='m "Awaria" hello'
Error: User 'Awaria' could not be found in your friends list!
    at getThreadByName.then.catch (/usr/lib/node_modules/messer/src/commands/command-handlers.js:59:13)

It Works from interactive mode when I receive the message first:

Successfully logged in as .................
> (Awaria) XXXXX - hmm

> m "Awaria" hello
Sent message to Awaria

### Versions

npm -v
6.4.1
messer -v
0.5.0
node -v
v10.15.3

**Comment by tomquirk** [comment]
Hey 👋 **Messer 0.5.1 has just been published** with a bunch of bug fixes - install it and give it a whirl 🤘. If you’re still experiencing this issue, please comment below with your symptoms and we'll keep the ticket open. Thanks for supporting Messer 💬

**Comment by tomquirk** [comment]
This issue hasn't had activity in 14 days, so we're assuming it was fixed in a previous release. If it's still an issue, please open a **new** ticket
